environment:
  my_variable:
    secure: JCSjKbmeUc+H++B2Ir3UaBL/XgnL9qAyPO++t5xrfCW9ku62GhkGx4XUx59Q7PqT
    
# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#before_test:
#  - ps: . .\Build.ps1

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\Build.ps1
#  - ps: Import-Module psake, BuildHelpers; Invoke-Psake .\Build.PSake.ps1; exit ( [int]( -not $psake.build_success ) )
